### PR TITLE
Adding holonomic/DP mode to path_follower_node

### PR DESCRIPTION
**Pull request by bsb808**
== Purpose ==

The functional change in this PR is to add a second "mode" to the path follower action execution.  The original path_follower only supports control for an underactuated vessel with non-holonomic kinematic constraints - e.g., a vessel with a single screw and rudder.  For the GFOE work, the USV has a dynamic positioning system, allowing it to actively control surge, sway and yaw independently (holonomic kinematics).  

The PR also separates out a header file to improve readability, documentation and maintenance.

It also exposes more ROS parameters to aid in tuning the controller - proportional gain in surge and sway, etc.

== Merge issues ==

There appears to be a merge issue in that the original GFOE fork was before commit 9520803cb0742c3a44c21d88809af569f375c117 on the upstream repo to "Periodically resend display"  

== Example ==  

Here is the launch file snippet we have been using for the "holonomic" dynamics_mode.

```
  <!-- path_follower --> 
  <arg name="cmd_vel_topic" value="piloting_mode/autonomous/cmd_vel"/>
  <arg name="enable_topic" value="piloting_mode/autonomous/active"/> 
  <arg name="base_frame" value="$(arg namespace)/base_link"/>
  <arg name="map_frame" value="$(arg namespace)/map"/>
  <node pkg="path_follower" type="path_follower_node"
	name="path_follower" ns="$(arg namespace)" output="screen">
    <remap from="cmd_vel" to="$(arg cmd_vel_topic)"/>
    <remap from="enable" to="$(arg enable_topic)"/>
    <param name="map_frame" value="$(arg map_frame)"/>
    <param name="base_frame" value="$(arg base_frame)"/>
    <param name="update_rate" value="10.0" type="double"/>
    <param name="dynamics_mode" value="holonomic"/>
    <param name="kp_surge" value="0.2" type="double"/>
    <param name="kp_sway" value="0.2" type="double"/>
    <param name="kp_yaw" value="0.25" type="double"/>
    <param name="turn_in_place" value="true" type="bool"/>
    <param name="turn_in_place_threshold" value="20.0" type="double"/>
  </node>
```

== Recommended Approach ==

@rolker - if you are interested in the additional functionality, I can probably merge in the current "noetic" branch to alleviate the merge conflicts.  

I also need to add documentation to the header file.

### CODE REVIEW

**Comment by rolker** [comment]
I'm giving merging a shot locally... 

Quick question, what's the reason for adding this-> to member variable access? I already start member variable names with m_ to reduce the chance of a local variable shadowing a member variable. I recognize that using this-> eliminates the possibility of such shadowing, but it also confuses the merge tools in this case!

I'm not necessarily opposed to adding this->, but I'm also not convinced that it's necessary.

**Comment by rolker** [comment]
Pushed the results of the merge to my repo and sent a PR to the gfoe repo to test modes other than the default.

**Comment by bsb808** [comment]
> Quick question, what's the reason for adding this-> to member variable access? I already start member variable names with m_ to reduce the chance of a local variable shadowing a member variable. I recognize that using this-> eliminates the possibility of such shadowing, but it also confuses the merge tools in this case!
> 
> I'm not necessarily opposed to adding this->, but I'm also not convinced that it's necessary.

It is certainly a stylistic issue.  I apologize for making the merge more of a challenge.

Using this-> is my habit of loosely following the Gazebo style guide: https://gazebosim.org/tutorials?tut=contrib_code&cat=development#Style

The ROS style guide call for a trailing underscore: http://wiki.ros.org/CppStyleGuide

Personally, I find the explicit this-> to be more explicit and readable than a naming convention - I'm never good about keeping up with naming conventions on various projects.

If you are up for including explicit this-> pointers, I can help with the merge.

**Comment by rolker** [comment]
I'm ok with keeping the this-> pointers. I did merge locally and sent a PR to GFOE fork to make sure it works for you. If you accept that PR, it should automatically update this PR if I understand Github correctly?

**Pull request merged**
